package support;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import domainmodel.HoaDonChiTiet;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import repository.impl.HoaDonChiTietRepository;
import viewmodel.QLHoaDonChiTiet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class In extends javax.swing.JFrame {

    private List<HoaDonChiTiet> listHD;

    public In(List<HoaDonChiTiet> list) {
        initComponents();
        this.listHD = list;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblemployer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblemployer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Noi", "2000"},
                {"2", "Hau", "3002"},
                {"3", "fdg", "333"},
                {"4", "dádasd", "3333"}
            },
            new String [] {
                "Employee ID", "Name", "Telephone"
            }
        ));
        jScrollPane1.setViewportView(tblemployer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String path = "";
        String header = "          Cửa Hàng Điện Thoại               /n";
        String header1 = "/n                             FPLOY HÀ NỘI /n";
        String header2 = "/n Ngày Tạo:                                /n";
        String header3 = "/n Họ tên Khách hàng                        /n";
        String header4 = "/n Nhân viên bán hàng";
        String header5 = "/nMã số: ";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }
        Document doc = new Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "fnam123.pdf"));
            doc.open();
            PdfPTable tbl = new PdfPTable(3);
            tbl.addCell("Mã Sản Phẩm");
            tbl.addCell("Tên Sản Phẩm");
            tbl.addCell("Số Lượng");
            tbl.addCell("Đơn Giá");
            tbl.addCell("Tổng Tiền");

            for (HoaDonChiTiet qLHoaDonChiTiet : listHD) {
                tbl.addCell(qLHoaDonChiTiet.getDienThoai().getMaDienThoai());
                tbl.addCell(qLHoaDonChiTiet.getDienThoai().getTenDienThoai());
                tbl.addCell(String.valueOf(qLHoaDonChiTiet.getDienThoai().getSoLuongTon()));
                tbl.addCell(String.valueOf(qLHoaDonChiTiet.getDonGia()));
                tbl.addCell(String.valueOf(qLHoaDonChiTiet.getTongTien(qLHoaDonChiTiet.getSoLuong())));
            }

//            for (int i = 0; i < tblemployer.getRowCount(); i++) {
//                String ID  = tblemployer.getValueAt(i,0).toString();
//                String name  = tblemployer.getValueAt(i,1).toString();
//                String  tele = tblemployer.getValueAt(i,2).toString();
//                tbl.addCell(ID);
//                tbl.addCell(name);
//                tbl.addCell(tele);
//            }
            doc.add(tbl);
            JOptionPane.showMessageDialog(null, "Doalf fdp", "not mess", JOptionPane.WARNING_MESSAGE);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(In.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(In.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblemployer;
    // End of variables declaration//GEN-END:variables
}
