/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import service.impl.DTNhaCungCapService;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.IDTNhaCungCapService;
import viewmodel.QLDTNhaCungCap;
import viewmodel.QLDienThoai;
import viewmodel.QLNhaCungCap;

/**
 *
 * @author Admin
 */
public class NhapDTNCC extends javax.swing.JFrame {

    private DefaultTableModel dtmDtNcc;
    private QLDienThoai dienThoai;
    private QLNhaCungCap nhaCungCap;
    private QLDTNhaCungCap dienThoaiNcc;
    private IDTNhaCungCapService dtNccService = new DTNhaCungCapService();
    private List<QLDTNhaCungCap> list = new ArrayList<>();

    public NhapDTNCC(java.awt.Frame parent, boolean modal, QLDienThoai dt, QLNhaCungCap ncc, DefaultTableModel dtm, QLDTNhaCungCap dtNcc, List<QLDTNhaCungCap> list) {
        initComponents();
        this.list = list;
        this.dienThoai = dt;
        this.nhaCungCap = ncc;
        this.dtmDtNcc = dtm;
        if (dtNcc == null) {
            btnSua.setEnabled(false);
        } else {
            this.dienThoaiNcc = dtNcc;
            btnThem.setEnabled(false);
            txtGiaTien.setText(String.valueOf(dienThoaiNcc.getGiaNhap()));
            txtSoLuong.setText(String.valueOf(dienThoaiNcc.getSoLuongNhap()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        txtGiaTien = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("So Luong");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Gia Tien");

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nhap Dien Thoai");

        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtGiaTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnHuy.setText("Huy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 324, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
             if (!"".equals(validateForm())) {
            JOptionPane.showMessageDialog(this, validateForm(), "Loi", JOptionPane.ERROR_MESSAGE);
        } else {
            QLDTNhaCungCap newDtNcc = new QLDTNhaCungCap();
            newDtNcc.setIdienThoai(dienThoai.getIdDienThoai());
            newDtNcc.setInhaCungCap(nhaCungCap.getId());
            newDtNcc.setManhaCungCap(nhaCungCap.getMa());
            newDtNcc.setMadienThoai(dienThoai.getMaDienThoai());
            newDtNcc.setNgayNhap(new Date());
            newDtNcc.setSoLuongNhap(Integer.valueOf(txtSoLuong.getText()));
            newDtNcc.setGiaNhap(new BigDecimal(txtGiaTien.getText()));
            list.add(newDtNcc);
            showDataTable();
            this.dispose();
             }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
//    QLDTNhaCungCap newDtNcc = new QLDTNhaCungCap();
//        newDtNcc.setId(dienThoaiNcc.getId());
//        newDtNcc.setIdienThoai(dienThoaiNcc.getIdienThoai());
//        newDtNcc.setInhaCungCap(dienThoaiNcc.getInhaCungCap());
//        newDtNcc.setMadienThoai(dienThoaiNcc.getMadienThoai());
//        newDtNcc.setManhaCungCap(dienThoaiNcc.getManhaCungCap());
//        newDtNcc.setSoLuongNhap(Integer.valueOf(txtSoLuong.getText()));
//        newDtNcc.setGiaNhap(new BigDecimal(txtGiaTien.getText()));
//        JOptionPane.showMessageDialog(this, dtNccService.update(newDtNcc));
//        list = dtNccService.getAll();
//        showDataTable();
//        this.dispose();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

   private void showDataTable() {
        dtmDtNcc.setRowCount(0);
        for (QLDTNhaCungCap x : list) {
            dtmDtNcc.addRow(new Object[]{ x.getMadienThoai(),x.getManhaCungCap(), x.getSoLuongNhap(), x.getGiaNhap()});
        }

    }
    private String validateForm() {
        String tb = "";
        if (txtGiaTien.getText().isEmpty()) {
            tb += "Khong duoc de trong gia tien";
        }
        if (txtSoLuong.getText().isEmpty()) {
            tb += " Khong duoc de trong so luong";
        }
        if (!tb.equals("")) {
            return tb;
        } else {
            if (!txtGiaTien.getText().matches("^\\d+$")) {
                tb += "Gia tien phai la so";
            }
            if (!txtSoLuong.getText().matches("^\\d+$")) {
                tb += "So luong phai la so";
            }
            return tb;
        }
    }


    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
