/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DongSanPham;
import model.MauSac;
import model.NhaSanXuat;
import model.SanPham;
import services.ChiTietSanPhamService;
import services.DongSanPhamService;
import services.MauSacService;
import services.NhaSanXuatService;
import services.SanPhamService;
import services.impl.ChiTietSanPhamServiceImpl;
import services.impl.DongSanPhamServiceImpl;
import services.impl.MauSacServiceImpl;
import services.impl.NhaSanXuatServiceImpl;
import services.impl.SanPhamServiceImpl;
import viewModel.ViewModelSanPham;

/**
 *
 * @author Admin
 */
public class ViewQuanLySanPham extends javax.swing.JFrame {

    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultComboBoxModel comboSP = new DefaultComboBoxModel();
    private DefaultComboBoxModel comboNSX = new DefaultComboBoxModel();
    private DefaultComboBoxModel comboDSP = new DefaultComboBoxModel();
    private DefaultComboBoxModel comboMS = new DefaultComboBoxModel();
    private DefaultComboBoxModel comboNamBaoHanh = new DefaultComboBoxModel();
    private List<ViewModelSanPham> listVMSP = new ArrayList<>();
    private List<Integer> listNamBaoHanh = new ArrayList<>();
    private List<SanPham> listSP = new ArrayList<>();
    private List<DongSanPham> listDSP = new ArrayList<>();
    private List<MauSac> listMS = new ArrayList<>();
    private List<NhaSanXuat> listNSX = new ArrayList<>();
    private ChiTietSanPhamService ctsps = new ChiTietSanPhamServiceImpl();
    private SanPhamService sps = new SanPhamServiceImpl();
    private DongSanPhamService dsps = new DongSanPhamServiceImpl();
    private NhaSanXuatService nsxs = new NhaSanXuatServiceImpl();
    private MauSacService mss = new MauSacServiceImpl();
    private int STT;
    private int row;

    public ViewQuanLySanPham() {
        initComponents();
        tbSanPham.setModel(dtm);
        cbbSanPham.setModel(comboSP);
        cbbDongSP.setModel(comboDSP);
        cbbMauSac.setModel(comboMS);
        cbbNSX.setModel(comboNSX);
        cbbTimKiem.setModel(comboNamBaoHanh);
        String[] header = {"STT", "MA SP", "TEN SP", "NSX", "MAU SAC", "DONG SP", "NAM BH", "MO TA", "SO LUONG TON", "GIA NHAP", "GIA BAN"};
        dtm.setColumnIdentifiers(header);
        listVMSP = ctsps.getListCTSP();
        listSP = sps.getSanPham();
        listDSP = dsps.getDongSanPham();
        listMS = mss.getMauSac();
        listNSX = nsxs.getNhaSanXuat();
        showDataTableCTSP(listVMSP);
        loadCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNamBH = new javax.swing.JTextField();
        txtSoLuongTon = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMoTa = new javax.swing.JTextArea();
        cbbSanPham = new javax.swing.JComboBox<>();
        cbbMauSac = new javax.swing.JComboBox<>();
        cbbDongSP = new javax.swing.JComboBox<>();
        cbbNSX = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        txtTenSP = new javax.swing.JTextField();
        txtTenMauSac = new javax.swing.JTextField();
        txtTenDongSP = new javax.swing.JTextField();
        txtTenNSX = new javax.swing.JTextField();
        btnThemNhanh = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        cbbTimKiem = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nam BH");

        jLabel2.setText("So Luong Ton");

        jLabel3.setText("Gia Nhap");

        jLabel4.setText("Gia ban");

        jLabel5.setText("Mo ta");

        jLabel6.setText("San Pham");

        jLabel7.setText("Mau Sac");

        jLabel8.setText("Dong SP");

        jLabel9.setText("Nha SX");

        txtAreaMoTa.setColumns(20);
        txtAreaMoTa.setRows(5);
        jScrollPane1.setViewportView(txtAreaMoTa);

        cbbSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSanPhamActionPerformed(evt);
            }
        });

        cbbMauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMauSacActionPerformed(evt);
            }
        });

        cbbDongSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbDongSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDongSPActionPerformed(evt);
            }
        });

        cbbNSX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNSXActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(89, 37));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(89, 37));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(89, 37));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.setPreferredSize(new java.awt.Dimension(89, 37));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.setPreferredSize(new java.awt.Dimension(89, 37));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbSanPham);

        txtTenSP.setEditable(false);
        txtTenSP.setBorder(null);

        txtTenMauSac.setEditable(false);
        txtTenMauSac.setBorder(null);

        txtTenDongSP.setEditable(false);
        txtTenDongSP.setBorder(null);

        txtTenNSX.setEditable(false);
        txtTenNSX.setBorder(null);
        txtTenNSX.setSelectedTextColor(new java.awt.Color(242, 242, 242));

        btnThemNhanh.setText("+");
        btnThemNhanh.setPreferredSize(new java.awt.Dimension(89, 37));
        btnThemNhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhanhActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.setPreferredSize(new java.awt.Dimension(89, 37));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cbbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbbNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTenNSX, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtTenDongSP, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtTenMauSac)
                            .addComponent(txtTenSP))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(211, 211, 211)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(cbbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(txtNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ViewBanHang newView = new ViewBanHang();
        newView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        ViewModelSanPham newModelSanPham = new ViewModelSanPham();
        newModelSanPham.setNamBH(Integer.valueOf(txtNamBH.getText()));
        newModelSanPham.setGiaBan(BigDecimal.valueOf(Double.valueOf(txtGiaBan.getText())));
        newModelSanPham.setGiaNhap(BigDecimal.valueOf(Double.valueOf(txtGiaNhap.getText())));
        newModelSanPham.setSoLuongTon(Integer.valueOf(txtSoLuongTon.getText()));
        newModelSanPham.setMoTa(txtAreaMoTa.getText());
        SanPham sp = sps.getByMaSP(String.valueOf(cbbSanPham.getSelectedItem()));
        newModelSanPham.setSanPham(sp);
        MauSac ms = mss.getByMaMauSac(String.valueOf(cbbMauSac.getSelectedItem()));
        newModelSanPham.setMauSac(ms);
        DongSanPham dsp = dsps.getByMaDSP(String.valueOf(cbbDongSP.getSelectedItem()));
        newModelSanPham.setDongSanPham(dsp);
        NhaSanXuat nsx = nsxs.getByMaNSX(String.valueOf(cbbNSX.getSelectedItem()));
        newModelSanPham.setNhaSanXuat(nsx);
        ctsps.saveCTSP(newModelSanPham);
        listVMSP = ctsps.getListCTSP();
        showDataTableCTSP(listVMSP);
    }//GEN-LAST:event_btnAddActionPerformed

    private void tbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMouseClicked
        row = tbSanPham.getSelectedRow();
        fillData(row);
    }//GEN-LAST:event_tbSanPhamMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        row = tbSanPham.getSelectedRow();
        ViewModelSanPham deleteSanPham = listVMSP.get(row);
        ctsps.deleteCTSP(deleteSanPham);
        listVMSP = ctsps.getListCTSP();
        showDataTableCTSP(listVMSP);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        row = tbSanPham.getSelectedRow();
        ViewModelSanPham updateSanPham = listVMSP.get(row);
        updateSanPham.setNamBH(Integer.valueOf(txtNamBH.getText()));
        updateSanPham.setGiaBan(BigDecimal.valueOf(Double.valueOf(txtGiaBan.getText())));
        updateSanPham.setGiaNhap(BigDecimal.valueOf(Double.valueOf(txtGiaNhap.getText())));
        updateSanPham.setSoLuongTon(Integer.valueOf(txtSoLuongTon.getText()));
        updateSanPham.setMoTa(txtAreaMoTa.getText());
        SanPham sp = sps.getByMaSP(String.valueOf(cbbSanPham.getSelectedItem()));
        updateSanPham.setSanPham(sp);
        MauSac ms = mss.getByMaMauSac(String.valueOf(cbbMauSac.getSelectedItem()));
        updateSanPham.setMauSac(ms);
        DongSanPham dsp = dsps.getByMaDSP(String.valueOf(cbbDongSP.getSelectedItem()));
        updateSanPham.setDongSanPham(dsp);
        NhaSanXuat nsx = nsxs.getByMaNSX(String.valueOf(cbbNSX.getSelectedItem()));
        updateSanPham.setNhaSanXuat(nsx);
        ctsps.updateCTSP(updateSanPham);
        listVMSP = ctsps.getListCTSP();
        showDataTableCTSP(listVMSP);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void cbbSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSanPhamActionPerformed
        SanPham sp = sps.getByMaSP(String.valueOf(cbbSanPham.getSelectedItem()));
        txtTenSP.setText(sp.getTenSP());
    }//GEN-LAST:event_cbbSanPhamActionPerformed

    private void cbbMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMauSacActionPerformed
        MauSac ms = mss.getByMaMauSac(String.valueOf(cbbMauSac.getSelectedItem()));
        txtTenMauSac.setText(ms.getTenMauSac());
    }//GEN-LAST:event_cbbMauSacActionPerformed

    private void cbbDongSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDongSPActionPerformed
        DongSanPham dsp = dsps.getByMaDSP(String.valueOf(cbbDongSP.getSelectedItem()));
        txtTenDongSP.setText(dsp.getTenDongSP());
    }//GEN-LAST:event_cbbDongSPActionPerformed

    private void cbbNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNSXActionPerformed
        NhaSanXuat nsx = nsxs.getByMaNSX(String.valueOf(cbbNSX.getSelectedItem()));
        txtTenNSX.setText(nsx.getTenNSX());
    }//GEN-LAST:event_cbbNSXActionPerformed

    private void btnThemNhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhanhActionPerformed
        ViewThemNhanhQuanLySanPham newView = new ViewThemNhanhQuanLySanPham();
        newView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThemNhanhActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        List<ViewModelSanPham> listSearch = ctsps.getCTSPByNamBaoHanh(Integer.valueOf(String.valueOf(cbbTimKiem.getSelectedItem())));
        if (listSearch.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Khong ton tai san pham");
            showDataTableCTSP(listVMSP);
        } else {
            showDataTableCTSP(listSearch);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void showDataTableCTSP(List<ViewModelSanPham> lists) {
        STT = 1;
        dtm.setRowCount(0);
        for (ViewModelSanPham x : lists) {
            dtm.addRow(new Object[]{STT++, x.getSanPham().getMaSP(), x.getSanPham().getTenSP(),
                x.getNhaSanXuat().getTenNSX(), x.getMauSac().getTenMauSac(), x.getDongSanPham().getTenDongSP(),
                x.getNamBH(), x.getMoTa(), x.getSoLuongTon(), x.getGiaNhap(), x.getGiaBan()});
        }
    }

    private void loadCombobox() {

        for (SanPham sp : listSP) {
            comboSP.addElement(sp.getMaSP());
        }

        for (DongSanPham dsp : listDSP) {
            comboDSP.addElement(dsp.getMaDongSP());
        }

        for (NhaSanXuat nsx : listNSX) {
            comboNSX.addElement(nsx.getMaNSX());
        }

        for (MauSac ms : listMS) {
            comboMS.addElement(ms.getMaMauSac());
        }

        for (int i = 1990; i <= 2000; i++) {
            listNamBaoHanh.add(i);
        }
        comboNamBaoHanh.addAll(listNamBaoHanh);
        comboNamBaoHanh.setSelectedItem("1990");

    }

    private void fillData(int index) {
        ViewModelSanPham newModelSanPham = listVMSP.get(index);
        cbbSanPham.setSelectedItem(newModelSanPham.getSanPham().getMaSP());
        cbbMauSac.setSelectedItem(newModelSanPham.getMauSac().getMaMauSac());
        cbbDongSP.setSelectedItem(newModelSanPham.getDongSanPham().getMaDongSP());
        cbbNSX.setSelectedItem(newModelSanPham.getNhaSanXuat().getMaNSX());
        txtNamBH.setText(String.valueOf(newModelSanPham.getNamBH()));
        txtAreaMoTa.setText(newModelSanPham.getMoTa());
        txtGiaBan.setText(String.valueOf(newModelSanPham.getGiaBan()));
        txtGiaNhap.setText(String.valueOf(newModelSanPham.getGiaNhap()));
        txtSoLuongTon.setText(String.valueOf(newModelSanPham.getSoLuongTon()));
    }

    private void clearForm() {
        tbSanPham.clearSelection();
        txtAreaMoTa.setText("");
        txtGiaBan.setText("");
        txtGiaNhap.setText("");
        txtNamBH.setText("");
        txtSoLuongTon.setText("");
        cbbDongSP.setSelectedIndex(0);
        cbbMauSac.setSelectedIndex(0);
        cbbNSX.setSelectedIndex(0);
        cbbSanPham.setSelectedIndex(0);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewQuanLySanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThemNhanh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbbDongSP;
    private javax.swing.JComboBox<String> cbbMauSac;
    private javax.swing.JComboBox<String> cbbNSX;
    private javax.swing.JComboBox<String> cbbSanPham;
    private javax.swing.JComboBox<String> cbbTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextArea txtAreaMoTa;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtNamBH;
    private javax.swing.JTextField txtSoLuongTon;
    private javax.swing.JTextField txtTenDongSP;
    private javax.swing.JTextField txtTenMauSac;
    private javax.swing.JTextField txtTenNSX;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
