package support;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import domainmodel.HoaDon;
import domainmodel.HoaDonChiTiet;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import repository.impl.HoaDonRepository;
import repository.impl.KhachHangRepository;
import swing.Home;
import static swing.Home.khachHangMua;
import static swing.Home.txtDiem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class In extends javax.swing.JFrame {

    /**
     * Creates new form In
     */
    List<HoaDonChiTiet> list;
    String soDiemDung;
    String tongTien;
    HoaDon hd;
    HoaDonRepository hoaDonRepo = new HoaDonRepository();

    public In() {
        initComponents();
    }

    public In(HoaDon hd, List<HoaDonChiTiet> list, String soDiemDung, String tongTien, String tienDuaString, String tienTra) {
        initComponents();
        this.list = list;
        this.tongTien = tongTien;
        this.soDiemDung = soDiemDung;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblemployer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Đồng ý");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblemployer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblemployer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String path = "D:\\";
//
//        JFileChooser j = new JFileChooser();
//        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
//        int x = j.showSaveDialog(this);
//        if (x == JFileChooser.APPROVE_OPTION) {
//            path = j.getSelectedFile().getPath();
//        }
        Document doc = new Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "fnam123.pdf"));
            doc.open();
            PdfPTable tbl = new PdfPTable(5);
            tbl.addCell("Ma San Pham");
            tbl.addCell("Ten San Pham");
            tbl.addCell("So Luong");
            tbl.addCell("Don Gia");
  //          tbl.addCell("Số tiền giảm");
            tbl.addCell("Thanh Tien");
            for (HoaDonChiTiet x : list) {
                tbl.addCell(x.ma());
                tbl.addCell(String.valueOf(x));
                tbl.addCell(String.valueOf(x.getSoLuong()));
                tbl.addCell(String.valueOf(x.getGia()));
//                tbl.addCell(String.valueOf(x.getCtkm().getSoTienGiam()));
                tbl.addCell(tongTien);
            }
//            for (int i = 0; i < tblemployer.getRowCount(); i++) {
//                String ten = tblemployer.getValueAt(i, 0).toString();
//                String name = tblemployer.getValueAt(i, 1).toString();
//                String soLuong = tblemployer.getValueAt(i, 2).toString();
//                String donGia = tblemployer.getValueAt(i, 2).toString();
//                String thanhTien = tblemployer.getValueAt(i, 2).toString();
//                tbl.addCell("SP1");
//                tbl.addCell(name);
//                tbl.addCell(soLuong);
//                tbl.addCell(donGia);
//                tbl.addCell(thanhTien);
//            }
            doc.add(tbl);
            JOptionPane.showMessageDialog(null, "Doalf fdp", "not mess", JOptionPane.WARNING_MESSAGE);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(In.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(In.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();

        //
//        if (!soDiemDung.equals("0")) {
//            hd.setDiemTichLuy(Integer.parseInt(txtDiem.getText()));
//            KhachHangRepository kh = new KhachHangRepository();
//            khachHangMua.setDiemTichLuy(0);
//            kh.update(khachHangMua, khachHangMua.getId());
//        }
//        hd.setList(list);
//        hd.setTrangThai(1);
//        hd.setKhachHang(khachHangMua);
//        hoaDonRepo.SaveOrUpdate(hd);
//        Home.fillToHoaDonIn();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new In().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblemployer;
    // End of variables declaration//GEN-END:variables
}
