/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package support;

import java.awt.print.PrinterException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sktfk
 */
public class LayHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form LayHoaDon
     */
    public LayHoaDon() {
        initComponents();
    }

    public void bill_print(JTable tblHoaDon) {
        int rowIndex = tblHoaDon.getSelectedRow();
        try {
            bill.setText("<<<N2>>>Cửa hàng bán điện thoại       \t PHIẾU THANH TOÁN \n");
            bill.setText(bill.getText() + " Đc:fpt poly ,Hà Nội ");
            DefaultTableModel dfk = (DefaultTableModel) tblHoaDon.getModel();

//                for (int i = 0; i < tblHoaDon.getRowCount(); i++) {
            String namek = dfk.getValueAt(rowIndex, 2).toString();

            bill.setText(bill.getText() + "\t  \t Ngày Tạo : " + namek + "\n");
//                bill.setText(bill.getText() + name+ "\n");

//            }
            bill.setText(bill.getText() + "  \n");
            bill.setText(bill.getText() + "Họ tên Khách hàng :\n");
            bill.setText(bill.getText() + "Nhân viên bán hàng :");
//            bill.setText(bill.getText() + "SDT :..... .......................");
            bill.setText(bill.getText() + "\t \t \t Mã số:\n");
            bill.setText(bill.getText() + "------------------------------------------------------------------------------------------------\n");
            bill.setText(bill.getText() + "Tên sản Phẩm \t SL \tđơn giá \t \tThành tiền \n");
//              lấy table
//            DefaultTableModel df = (DefaultTableModel) tblHoaDonChiTiet.getModel();
//            for (int i = 0; i < tblHoaDonChiTiet.getRowCount(); i++) {
//
//                String name = df.getValueAt(i, 0).toString();
//                String qt = df.getValueAt(i, 1).toString();
//                String prc = df.getValueAt(i, 2).toString();
//                String prca = df.getValueAt(i, 3).toString();
//
//                bill.setText(bill.getText() + name + "\t" + qt + "\t" + prc + "\t" + prca + "\n");
//
//            }

            bill.setText(bill.getText() + "  \n");
            bill.setText(bill.getText() + "  \n");
            bill.setText(bill.getText() + "  \n");
            bill.setText(bill.getText() + "--------------------------------------------------------------------------------------------------------\n");
            bill.setText(bill.getText() + "Số tiền giảm :\n");
            bill.setText(bill.getText() + "Tổng tiền :\n");
            bill.setText(bill.getText() + "Tiền khách đưa :\n");
            bill.setText(bill.getText() + "Tiền trả khách :\n");
//            lấy text
//            bill.setText(bill.getText() + "SubTotal :\t"+Too.getText()+"\n");
//            bill.setText(bill.getText() + "Cash :\t"+Cash.getText()+"\n");
//            bill.setText(bill.getText() + "Ballance :\t"+Bal.getText()+"\n");
            bill.setText(bill.getText() + "Người lập phiếu \t");
            bill.setText(bill.getText() + "Khách hàng\t");
            bill.setText(bill.getText() + "Thu ngân\n");
            bill.setText(bill.getText() + "Ký(Họ Tên) ");

            bill.setText(bill.getText() + "\t \t \t Ký(Họ Tên) \n");

            bill.setText(bill.getText() + "  \n");
            bill.setText(bill.getText() + "  \n");
            bill.setText(bill.getText() + "  \n");
            bill.setText(bill.getText() + "====================================\n");

            bill.print();

        } catch (PrinterException ex) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bill.setColumns(20);
        bill.setRows(5);
        jScrollPane1.setViewportView(bill);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bill;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
